=== ddoodm/WebServicesTeamTwo/WebContent/WEB-INF/hotels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.uts.edu.au/31284/team2/wsd-hotels"
 xmlns="http://www.uts.edu.au/31284/team2/wsd-hotels"
 elementFormDefault="qualified">
 
 <xs:element name="hotels">
 	<xs:complexType>
 		<xs:sequence minOccurs="1" maxOccurs="unbounded">
 			<xs:element name="hotel" type="hotelType" />
 		</xs:sequence>
 	</xs:complexType>
 </xs:element>
 
 <xs:complexType name="hotelType">
 	<xs:sequence>
 		<xs:element name="name" type="nameType" />
 		<xs:element name="country" type="nameType" />
 		<xs:element name="rating" type="ratingType" />
 		<xs:element name="image-url" type="imageUrlType" />
 		<xs:element name="description" type="xs:string" />
 	</xs:sequence>
 	
 	<xs:attribute name="id" type="xs:unsignedInt" use="required"/>
 </xs:complexType>
 
 <xs:simpleType name="ratingType">
 	<xs:restriction base="xs:unsignedShort">
    	<xs:minInclusive value="1"/>
    	<xs:maxInclusive value="10"/>
  	</xs:restriction>
 </xs:simpleType>
 
  <xs:simpleType name="nameType">
 	<xs:restriction base="xs:string">
    	<xs:pattern value="([A-Z]'?[-aA-zZ]+\s?)+"/>
  	</xs:restriction>
 </xs:simpleType>
 
 <xs:simpleType name="imageUrlType">
 	<xs:restriction base="xs:string">
    	<xs:pattern value="([\-_a-zA-Z0-9]+)(/[\-_a-zA-Z0-9]+)*.(jpg|png|gif|tif|bmp|tga)"/>
  	</xs:restriction>
 </xs:simpleType>
 
</xs:schema>

=== ddoodm/WebServicesTeamTwo/WebContent/WEB-INF/hotels.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hotels.xsl"?>

<d:hotels
	xmlns:d="http://www.uts.edu.au/31284/team2/wsd-hotels"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uts.edu.au/31284/team2/wsd-hotels hotels.xsd ">
	
  <d:hotel id="1">
    <d:name>Test Hotel</d:name>
    <d:country>Australia</d:country>
  </d:hotel>
  
  <d:hotel id="2">
    <d:name>Best Inn</d:name>
    <d:country>USA</d:country>
  </d:hotel>
  
  <d:hotel id="3">
    <d:name>Better Inn</d:name>
    <d:country>Canada</d:country>
  </d:hotel>
  
</d:hotels>
